on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux]
        goarch: [amd64]

    steps:
    - uses: actions/checkout@v3
    - run: |
        apt-get update
        apt-get install -y curl git meson cmake fuse3 libfuse3-dev autoconf make gcc
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.21.5.linux-amd64.tar.gz"
        project_path: .
        binary_name: "sandbox"
        sha256sum: TRUE
        md5sum: TRUE
        ldflags: "-s -w"